name: Descargar TRM diaria

on:
  schedule:
    - cron: '0 4 * * *'  # Ejecutar a las 4:00 AM UTC todos los días
  workflow_dispatch:

jobs:
  download_trm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Run script
      run: |
        python descargar_trm_diaria.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add trm_diaria.csv
        git commit -m "Update TRM diaria" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Show log files
      run: |
        cat trm_diaria.csv